# ဒီပရိုဂရမ်ကို run လိုက်တဲ့အခါ ပထမ operation 
# က timeout ဖြစ်သွားပြီး
# ဒုတိယ operation success ဖြစ်တာ တွေ့ရပါတယ်။
$ go run timeouts.go 
timeout 1
result 2
